#!/usr/bin/env bash
# Download the theme fonts (SIL Open Font License 1.1) from the @fontsource
# npm packages and generate assets/css/fonts.css. The downloaded files are
# committed; re-run only to change fonts or weights.
set -euo pipefail
cd "$(dirname "$0")/.."

VER=5   # @fontsource major version
DEST=static/fonts
CSS=assets/css/fonts.css
CDN=https://cdn.jsdelivr.net/npm/@fontsource
LATIN='U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD'
LATIN_EXT='U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF'

mkdir -p "$DEST" "$(dirname "$CSS")"
{
  echo "/* Generated by scripts/fetch-fonts.sh -- do not edit. Fonts: SIL OFL 1.1, see /fonts/LICENSE-*.txt */"
  for spec in "space-grotesk:Space Grotesk:400 500 600 700" \
              "ibm-plex-sans:IBM Plex Sans:400 500 600" \
              "ibm-plex-mono:IBM Plex Mono:400 500"; do
    IFS=: read -r pkg family weights <<<"$spec"
    curl -fsSL -o "$DEST/LICENSE-$pkg.txt" "$CDN/$pkg@$VER/LICENSE"
    for w in $weights; do
      for subset in latin-ext latin; do
        file="$pkg-$subset-$w-normal.woff2"
        curl -fsSL -o "$DEST/$file" "$CDN/$pkg@$VER/files/$file"
        range=$LATIN
        [ "$subset" = latin-ext ] && range=$LATIN_EXT
        printf "@font-face{font-family:'%s';font-style:normal;font-weight:%s;font-display:swap;src:url(../fonts/%s) format('woff2');unicode-range:%s}\n" \
          "$family" "$w" "$file" "$range"
      done
    done
  done
} > "$CSS"
